#!/usr/bin/env python3
"""
Generate sitemap.xml and _redirects from the filesystem.

Discovers indexable HTML pages in the project root, rankings/, and restaurants/.
Excludes underscore-prefixed working files and thank-you.html (noindexed; also
deliberately kept out of _redirects -- see build_redirects).

Both artifacts come from the same page enumeration so a new page cannot ship
in the sitemap without its redirect rule (or vice versa):

    sitemap.xml   <loc> entries are the extension-less URLs the pages'
                  canonicals declare.
    _redirects    one forced 301 per page from the physical .html path to
                  the extension-less URL.

Run from project root:
    python scripts/generate_sitemap.py
"""

import json
import re
from pathlib import Path
from xml.etree.ElementTree import Element, SubElement, ElementTree, indent

SITE_URL = "https://votedonbylocals.com"
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Directories to scan, mapped to their URL prefix.
SCAN_DIRS = {
    "": "/",
    "rankings": "/rankings/",
    "restaurants": "/restaurants/",
}

EXCLUDE_FILES = {"thank-you.html"}


def extract_dateModified_from_html(filepath):
    """Parse the JSON-LD <script> block; return dateModified value or None.

    Handles both page shapes: a single-location page's flat node, and a
    multi-location page's `@graph`, where the dates live on the brand
    Organization node. Without the @graph branch every multi-location page
    would silently lose its <lastmod>.
    """
    try:
        text = filepath.read_text(encoding="utf-8")
    except OSError:
        return None
    m = re.search(
        r'<script type="application/ld\+json">(.+?)</script>',
        text, re.DOTALL,
    )
    if not m:
        return None
    try:
        data = json.loads(m.group(1))
    except json.JSONDecodeError:
        return None
    if not isinstance(data, dict):
        return None
    if "dateModified" in data:
        return data["dateModified"]
    for node in data.get("@graph") or []:
        if isinstance(node, dict) and "dateModified" in node:
            return node["dateModified"]
    return None


def discover_pages():
    """Return list of (html_path, clean_path, lastmod_or_None) tuples.

    html_path is the site-relative path of the physical file, e.g.
    "/rankings/best-pizza.html". clean_path is the extension-less URL the
    site serves and the page's canonical declares ("/" for the homepage).
    """
    entries = []
    for subdir, url_prefix in SCAN_DIRS.items():
        scan_path = PROJECT_ROOT / subdir if subdir else PROJECT_ROOT
        for html in sorted(scan_path.glob("*.html")):
            name = html.name
            if name.startswith("_") or name in EXCLUDE_FILES:
                continue
            html_path = f"{url_prefix}{name}"
            if subdir == "" and name == "index.html":
                clean_path = "/"
            else:
                clean_path = f"{url_prefix}{name.removesuffix('.html')}"
            lastmod = extract_dateModified_from_html(html)
            entries.append((html_path, clean_path, lastmod))
    return entries


def build_sitemap(entries):
    NS = "http://www.sitemaps.org/schemas/sitemap/0.9"
    root = Element("urlset", xmlns=NS)
    for _, clean_path, lastmod in entries:
        url_el = SubElement(root, "url")
        SubElement(url_el, "loc").text = f"{SITE_URL}{clean_path}"
        if lastmod is not None:
            SubElement(url_el, "lastmod").text = lastmod
    tree = ElementTree(root)
    indent(tree, space="  ")
    return tree


def build_redirects(entries):
    """Build the Netlify _redirects file: one forced 301 per page, .html
    path -> extension-less path. Forced (301!) because the .html files
    exist in the deploy and Netlify only shadows existing paths with
    forced rules.

    thank-you.html is deliberately absent (via EXCLUDE_FILES): the vote
    form posts to /thank-you.html, and a forced redirect on a Netlify
    form action path risks breaking submissions.
    """
    lines = [
        "# Generated by scripts/generate_sitemap.py -- do not edit by hand.",
        "# One forced 301 per page: the physical .html path redirects to the",
        "# extension-less URL the page's canonical declares. thank-you.html is",
        "# deliberately absent: the vote form posts to /thank-you.html, and a",
        "# forced redirect on a Netlify form action path risks breaking",
        "# submissions.",
    ]
    for html_path, clean_path, _ in entries:
        lines.append(f"{html_path} {clean_path} 301!")
    return "\n".join(lines) + "\n"


def main():
    entries = discover_pages()

    tree = build_sitemap(entries)
    sitemap_out = PROJECT_ROOT / "sitemap.xml"
    tree.write(sitemap_out, encoding="utf-8", xml_declaration=True)

    redirects_out = PROJECT_ROOT / "_redirects"
    with redirects_out.open("w", encoding="utf-8", newline="\n") as f:
        f.write(build_redirects(entries))

    n_lastmod = sum(1 for _, _, lm in entries if lm is not None)
    print(f"Wrote {sitemap_out} with {len(entries)} URLs ({n_lastmod} with <lastmod>).")
    print(f"Wrote {redirects_out} with {len(entries)} redirect rules.")
    for _, clean_path, lastmod in entries:
        suffix = f"  [lastmod: {lastmod}]" if lastmod else ""
        print(f"  {SITE_URL}{clean_path}{suffix}")


if __name__ == "__main__":
    main()
