#!/usr/bin/env python3
"""
Build-time inliner for header/footer chrome with marker-wrapped output and a
divergence-detecting --check mode.

Replaces these placeholders across all production HTML pages:
  <header id="main-header"></header>  → contents of components/header.html
  <footer id="main-footer"></footer>  → contents of components/footer.html

Inlined content is wrapped in HTML comment markers:
    <!-- AUTOGENERATED FROM components/header.html — DO NOT EDIT INLINE -->
    <nav>...</nav>
    <!-- /AUTOGENERATED -->

Markers serve double duty: human warning to future editors that inline
edits will be overwritten on next inliner run, AND machine boundary for
the --check mode that detects divergence between inlined content and the
components/ source-of-truth.

Per-region state machine (header and footer treated independently):
  - placeholder present, marker absent  → 'inline'   (fresh inline)
  - placeholder absent,  marker present → 'skip'     (already done)
  - placeholder absent,  marker absent  → 'retrofit' (wrap existing inlined
                                                      content; PR #7 era)
  - placeholder present, marker present → 'fail'     (inconsistent — halt)

Two-pass (validate-then-apply) — halts loudly if any file's state is
inconsistent or a retrofit target can't be located.

Run from project root:
    python scripts/inline_chrome.py            # inline + retrofit
    python scripts/inline_chrome.py --check    # detect divergence
    python scripts/inline_chrome.py --check --verbose  # plus per-file diff

--check exit codes:
    0 — all files in sync (56 as of 2026-08-25; the count grows with each launch)
    1 — divergence detected
    2 — markers missing on at least one region (post-retrofit error)
"""

import argparse
import difflib
import re
import sys
import textwrap
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SCAN_DIRS = ["", "rankings", "restaurants"]

HEADER_PLACEHOLDER = '<header id="main-header"></header>'
FOOTER_PLACEHOLDER = '<footer id="main-footer"></footer>'

HEADER_MARKER_START = '<!-- AUTOGENERATED FROM components/header.html — DO NOT EDIT INLINE -->'
HEADER_MARKER_END = '<!-- /AUTOGENERATED -->'
FOOTER_MARKER_START = '<!-- AUTOGENERATED FROM components/footer.html — DO NOT EDIT INLINE -->'
FOOTER_MARKER_END = '<!-- /AUTOGENERATED -->'


def discover_files():
    files = []
    for subdir in SCAN_DIRS:
        scan_path = PROJECT_ROOT / subdir if subdir else PROJECT_ROOT
        for html in sorted(scan_path.glob("*.html")):
            files.append(html)
    return files


def load_components():
    return (
        (PROJECT_ROOT / "components" / "header.html").read_text(encoding="utf-8"),
        (PROJECT_ROOT / "components" / "footer.html").read_text(encoding="utf-8"),
    )


def categorize_region(html, placeholder, marker_start):
    """Return one of 'inline' | 'skip' | 'retrofit' | 'fail'."""
    has_ph = placeholder in html
    has_marker = marker_start in html
    if has_ph and not has_marker:
        return 'inline'
    if not has_ph and has_marker:
        return 'skip'
    if not has_ph and not has_marker:
        return 'retrofit'
    return 'fail'


def _indent_block(text, indent):
    """Prepend `indent` to every non-empty line."""
    return '\n'.join(
        (indent + line if line else line) for line in text.split('\n')
    )


def inline_with_markers(html, placeholder, component_text, marker_start, marker_end):
    """Replace the placeholder line with marker_start + indented component +
    marker_end. Returns (new_html, found_bool).
    """
    pattern = re.compile(
        r'(^|\n)([ \t]*)' + re.escape(placeholder),
        re.MULTILINE,
    )
    m = pattern.search(html)
    if not m:
        return html, False
    prefix, indent = m.group(1), m.group(2)
    component = component_text.rstrip('\n')
    indented = _indent_block(component, indent)
    new_block = (
        prefix + indent + marker_start + '\n'
        + indented + '\n'
        + indent + marker_end
    )
    return html[:m.start()] + new_block + html[m.end():], True


def find_inlined_block(html, component_text):
    """Find an existing inlined component in `html`. Return (start, end, indent)
    or None if not located. `start` and `end` bound the inlined block; `indent`
    is the leading whitespace prefix used at inline time.
    """
    component = component_text.rstrip('\n')
    component_lines = component.split('\n')
    first_line = component_lines[0]
    if not first_line:
        return None
    pattern = re.compile(
        r'(^|\n)([ \t]*)' + re.escape(first_line),
        re.MULTILINE,
    )
    for m in pattern.finditer(html):
        indent = m.group(2)
        expected = _indent_block(component, indent)
        block_start = m.start() + len(m.group(1))
        block_end = block_start + len(expected)
        if html[block_start:block_end] == expected:
            return (block_start, block_end, indent)
    return None


def retrofit_with_markers(html, component_text, marker_start, marker_end):
    """Wrap an existing inlined block with markers. Returns (new_html, found_bool)."""
    result = find_inlined_block(html, component_text)
    if result is None:
        return html, False
    block_start, block_end, indent = result
    new_text = (
        html[:block_start]
        + indent + marker_start + '\n'
        + html[block_start:block_end]
        + '\n' + indent + marker_end
        + html[block_end:]
    )
    return new_text, True


def strip_marker_block(html, marker_start, marker_end, placeholder):
    """Find marker_start...marker_end block in html and replace it with the
    placeholder line at the marker's original indent. Returns (new_html,
    found_bool).

    Raises ValueError if marker_start is present but marker_end is not (a
    malformed file — caller should halt).
    """
    pattern = re.compile(
        r'(^|\n)([ \t]*)' + re.escape(marker_start),
        re.MULTILINE,
    )
    m = pattern.search(html)
    if not m:
        return html, False
    prefix, indent = m.group(1), m.group(2)
    block_start = m.start()
    end_search_from = m.end()
    e = html.find(marker_end, end_search_from)
    if e == -1:
        raise ValueError(
            f"Marker block malformed: found {marker_start!r} but no matching "
            f"{marker_end!r} after it"
        )
    block_end = e + len(marker_end)
    return html[:block_start] + prefix + indent + placeholder + html[block_end:], True


def extract_between_markers(html, marker_start, marker_end):
    """Return content between markers, or None if either marker is absent.

    The end marker lives on its own line at the same indent as the start
    marker, so we walk back from the end marker's position past its leading
    indent and past the newline that separates it from the block content.
    """
    s = html.find(marker_start)
    if s == -1:
        return None
    content_start = s + len(marker_start)
    if content_start < len(html) and html[content_start] == '\n':
        content_start += 1
    e = html.find(marker_end, content_start)
    if e == -1:
        return None
    content_end = e
    # Strip the indent on the marker_end's own line.
    while content_end > content_start and html[content_end - 1] in ' \t':
        content_end -= 1
    # Strip the newline that separates the block content from marker_end.
    if content_end > content_start and html[content_end - 1] == '\n':
        content_end -= 1
    return html[content_start:content_end]


def _normalize_blank_lines(text):
    """Replace whitespace-only lines with empty strings.

    `textwrap.dedent` normalizes whitespace-only lines on its output but
    we also need to apply this to the component-side text we're comparing
    against, otherwise a 12-space "blank" line in components/* shows up
    as divergence vs. the dedented inlined version.
    """
    return '\n'.join(
        '' if line.strip() == '' else line
        for line in text.split('\n')
    )


def is_in_sync(extracted, component):
    """Compare dedented extracted content to component, normalizing
    whitespace-only lines on both sides and trimming trailing newlines.
    """
    a = _normalize_blank_lines(textwrap.dedent(extracted))
    b = _normalize_blank_lines(component)
    return a.rstrip('\n') == b.rstrip('\n')


def make_diff(extracted, component, region):
    a = _normalize_blank_lines(textwrap.dedent(extracted)).rstrip('\n') + '\n'
    b = _normalize_blank_lines(component).rstrip('\n') + '\n'
    return ''.join(difflib.unified_diff(
        a.splitlines(keepends=True),
        b.splitlines(keepends=True),
        fromfile=f'inlined ({region})',
        tofile=f'components/{region}.html',
    ))


def run_inline():
    files = discover_files()
    print(f"Discovered {len(files)} HTML pages.")

    header_text, footer_text = load_components()

    actions = {}
    failures = {}

    for f in files:
        text = f.read_text(encoding='utf-8')
        h_state = categorize_region(text, HEADER_PLACEHOLDER, HEADER_MARKER_START)
        f_state = categorize_region(text, FOOTER_PLACEHOLDER, FOOTER_MARKER_START)
        if h_state == 'fail' or f_state == 'fail':
            failures[f] = f"header={h_state}, footer={f_state} (placeholder+marker both present)"
            continue
        if h_state == 'retrofit' and find_inlined_block(text, header_text) is None:
            failures[f] = "header retrofit: existing inlined block not found"
            continue
        if f_state == 'retrofit' and find_inlined_block(text, footer_text) is None:
            failures[f] = "footer retrofit: existing inlined block not found"
            continue
        actions[f] = (h_state, f_state)

    if failures:
        print(f"\nHALT: {len(failures)} file(s) in inconsistent state. No files modified.")
        for f, msg in failures.items():
            print(f"  {f.relative_to(PROJECT_ROOT)}: {msg}")
        return 1

    skipped = sum(1 for h, fs in actions.values() if h == 'skip' and fs == 'skip')
    pending = {f: states for f, states in actions.items() if states != ('skip', 'skip')}

    if skipped:
        print(f"Skipping {skipped} already-marked file(s).")

    if not pending:
        print("Nothing to inline or retrofit.")
        return 0

    n_inline = 0
    n_retrofit = 0
    for f, (h_state, f_state) in pending.items():
        text = f.read_text(encoding='utf-8')
        if h_state == 'inline':
            text, _ = inline_with_markers(text, HEADER_PLACEHOLDER, header_text, HEADER_MARKER_START, HEADER_MARKER_END)
            n_inline += 1
        elif h_state == 'retrofit':
            text, _ = retrofit_with_markers(text, header_text, HEADER_MARKER_START, HEADER_MARKER_END)
            n_retrofit += 1
        if f_state == 'inline':
            text, _ = inline_with_markers(text, FOOTER_PLACEHOLDER, footer_text, FOOTER_MARKER_START, FOOTER_MARKER_END)
            n_inline += 1
        elif f_state == 'retrofit':
            text, _ = retrofit_with_markers(text, footer_text, FOOTER_MARKER_START, FOOTER_MARKER_END)
            n_retrofit += 1
        f.write_text(text, encoding='utf-8')
        labels = []
        if h_state in ('inline', 'retrofit'):
            labels.append(f"header:{h_state}")
        if f_state in ('inline', 'retrofit'):
            labels.append(f"footer:{f_state}")
        print(f"  {f.relative_to(PROJECT_ROOT)} ({', '.join(labels)})")

    print(f"\nProcessed {len(pending)} files (inline: {n_inline}, retrofit: {n_retrofit}).")
    return 0


def run_check(verbose=False):
    files = discover_files()
    header_text, footer_text = load_components()

    missing = []
    divergent = []

    for f in files:
        text = f.read_text(encoding='utf-8')
        for region, marker_start, marker_end, component in [
            ('header', HEADER_MARKER_START, HEADER_MARKER_END, header_text),
            ('footer', FOOTER_MARKER_START, FOOTER_MARKER_END, footer_text),
        ]:
            extracted = extract_between_markers(text, marker_start, marker_end)
            if extracted is None:
                missing.append((f, region))
                continue
            if not is_in_sync(extracted, component):
                divergent.append((f, region, extracted, component))

    if missing:
        print(f"[FAIL] {len(missing)} region(s) missing markers:")
        for f, region in missing:
            print(f"  {f.relative_to(PROJECT_ROOT)} ({region})")
        return 2

    if divergent:
        print(f"[FAIL] Divergence detected in {len(divergent)} region(s):")
        for f, region, _, _ in divergent:
            print(f"  {f.relative_to(PROJECT_ROOT)}: {region} inlined chrome differs from components/{region}.html")
        if verbose:
            print()
            for f, region, extracted, component in divergent:
                print(f"--- {f.relative_to(PROJECT_ROOT)} ({region}) ---")
                sys.stdout.write(make_diff(extracted, component, region))
        else:
            print("\nRe-run with --verbose for line-level diff.")
        return 1

    print(f"[OK] {len(files)} files in sync")
    return 0


def run_refresh():
    """Strip existing marker-wrapped chrome and re-inline from components/*.html.

    For each file:
      1. Validate marker pairs (start with no matching end → halt).
      2. Strip header marker block back to HEADER_PLACEHOLDER (if present).
      3. Strip footer marker block back to FOOTER_PLACEHOLDER (if present).
      4. Run inline_with_markers for each region that had markers, producing
         fresh marker-wrapped content from current components/*.html.

    Regions without markers are skipped with a warning (not an error) — this
    handles the unusual case of a file whose markers were removed manually
    or that was never retrofitted.
    """
    files = discover_files()
    print(f"Discovered {len(files)} HTML pages.")

    header_text, footer_text = load_components()

    failures = {}
    file_states = {}

    for f in files:
        text = f.read_text(encoding='utf-8')
        has_h_start = HEADER_MARKER_START in text
        has_h_end = HEADER_MARKER_END in text
        has_f_start = FOOTER_MARKER_START in text
        # FOOTER_MARKER_END is the same string as HEADER_MARKER_END, so its
        # presence/count is verified by counting <!-- /AUTOGENERATED --> overall.
        end_count = text.count(HEADER_MARKER_END)
        start_count = (1 if has_h_start else 0) + (1 if has_f_start else 0)
        if end_count != start_count:
            failures[f] = (
                f"marker pair mismatch: starts={start_count}, ends={end_count}"
            )
            continue
        file_states[f] = (has_h_start, has_f_start)

    if failures:
        print(f"\nHALT: {len(failures)} file(s) have malformed markers. No files modified.")
        for f, msg in failures.items():
            print(f"  {f.relative_to(PROJECT_ROOT)}: {msg}")
        return 1

    refreshed = 0
    warned = 0
    for f, (has_h, has_ftr) in file_states.items():
        if not has_h:
            print(f"  warning: {f.relative_to(PROJECT_ROOT)} - header markers missing, region not refreshed")
            warned += 1
        if not has_ftr:
            print(f"  warning: {f.relative_to(PROJECT_ROOT)} - footer markers missing, region not refreshed")
            warned += 1
        if not has_h and not has_ftr:
            continue
        text = f.read_text(encoding='utf-8')
        if has_h:
            text, _ = strip_marker_block(text, HEADER_MARKER_START, HEADER_MARKER_END, HEADER_PLACEHOLDER)
        if has_ftr:
            text, _ = strip_marker_block(text, FOOTER_MARKER_START, FOOTER_MARKER_END, FOOTER_PLACEHOLDER)
        if has_h:
            text, _ = inline_with_markers(text, HEADER_PLACEHOLDER, header_text, HEADER_MARKER_START, HEADER_MARKER_END)
        if has_ftr:
            text, _ = inline_with_markers(text, FOOTER_PLACEHOLDER, footer_text, FOOTER_MARKER_START, FOOTER_MARKER_END)
        f.write_text(text, encoding='utf-8')
        refreshed += 1
        print(f"  refreshed: {f.relative_to(PROJECT_ROOT)}")

    print(f"\nRefreshed {refreshed} file(s).{f' ({warned} region warning(s).)' if warned else ''}")
    return 0


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Inline header/footer chrome from components/ into all production "
            "HTML pages, with marker-wrapped output, a --check mode for "
            "detecting divergence, and a --refresh mode for re-inlining "
            "after components/ edits."
        ),
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        '--check', action='store_true',
        help="Detect divergence; do not modify files. Exit 0 = synced, 1 = divergent, 2 = missing markers.",
    )
    mode.add_argument(
        '--refresh', action='store_true',
        help="Strip existing marker-wrapped chrome and re-inline from components/*.html. "
             "Use after editing components/.",
    )
    parser.add_argument(
        '--verbose', action='store_true',
        help="With --check, print unified diff per divergent region.",
    )
    args = parser.parse_args()

    if args.check:
        sys.exit(run_check(args.verbose))
    elif args.refresh:
        sys.exit(run_refresh())
    else:
        sys.exit(run_inline())


if __name__ == "__main__":
    main()
